#!/usr/bin/env julia
# Duktape Hub package — deep integration test
#
# Assumes the wrapper is already built (test.jl rebuilds; this only verifies).
# ECMAScript semantics are the oracle: every assertion below is a program whose
# result the language specification fixes, so agreement is evidence about the
# wrapped engine rather than about the wrapper's opinion of it.
#   - heap lifecycle, value stack discipline, every type tag
#   - the macro-shim family (duk_eval_string / duk_peval_string /
#     duk_safe_to_string / duk_is_callable) — 40-odd shims are the bulk of this
#     package's config, and a shim that resolved a foreign duktape.h would give
#     wrong answers with no other symptom
#   - protected vs unprotected evaluation, error objects and error codes
#   - objects, arrays, properties, JSON encode/decode round-trips
#   - Julia @cfunction native functions callable FROM JavaScript, including one
#     that throws back into the engine
#   - Tier-1 liveness and churn under GC pressure
#
# NOTE: this package tracks svaarala/duktape-RELEASES, not the main repo — the
# main repo ships no duktape.c at all (it is generated by tools/configure.py).
#
# Usage:  julia --project=/path/to/RepliBuild.jl packages/duktape/test_deep.jl

using Test
using InteractiveUtils: code_typed

const PKG_DIR = @__DIR__
const WRAPPER = joinpath(PKG_DIR, "julia", "Duktape.jl")

if !isfile(WRAPPER)
    @info "Wrapper missing — building first"
    using RepliBuild
    RepliBuild.build(joinpath(PKG_DIR, "replibuild.toml"))
    RepliBuild.wrap(joinpath(PKG_DIR, "replibuild.toml"))
end

include(WRAPPER)

const D = Duktape

function kernel_emits_llvmcall(kernel)
    ms = collect(methods(kernel))
    isempty(ms) && error("no method for $kernel")
    argtypes = Base.tuple_type_tail(ms[1].sig)
    ct = code_typed(kernel, argtypes)
    isempty(ct) && error("code_typed empty for $kernel with $argtypes")
    return occursin("llvmcall", string(ct))
end

# duktape type tags (duk_config.h / duktape.h #defines)
const DUK_TYPE_NONE, DUK_TYPE_UNDEFINED, DUK_TYPE_NULL = 0, 1, 2
const DUK_TYPE_BOOLEAN, DUK_TYPE_NUMBER, DUK_TYPE_STRING = 3, 4, 5
const DUK_TYPE_OBJECT, DUK_TYPE_BUFFER, DUK_TYPE_POINTER = 6, 7, 8
const DUK_EXEC_SUCCESS, DUK_EXEC_ERROR = 0, 1
# Verbatim from duktape.h (v2.7.0). Getting these wrong is silent — the engine
# just reports a different error class — so they are transcribed, not guessed.
const DUK_ERR_NONE = 0
const DUK_ERR_ERROR = 1
const DUK_ERR_EVAL_ERROR = 2
const DUK_ERR_RANGE_ERROR = 3
const DUK_ERR_REFERENCE_ERROR = 4
const DUK_ERR_SYNTAX_ERROR = 5
const DUK_ERR_TYPE_ERROR = 6
const DUK_ERR_URI_ERROR = 7
const DUK_RET_TYPE_ERROR = -DUK_ERR_TYPE_ERROR

"Create a heap, run `f(ctx)`, always destroy."
function withheap(f)
    ctx = D.duk_create_heap_default()
    ctx == C_NULL && error("duk_create_heap_default returned NULL")
    try
        return f(ctx)
    finally
        D.duk_destroy_heap(ctx)
    end
end

"Evaluate `src` (protected) and return the result coerced to a String."
function evalstr(ctx, src)
    rc = D.duk_peval_string(ctx, src)
    s = D.duk_safe_to_string(ctx, -1)
    D.duk_pop(ctx)
    return (rc, s)
end

# ── Native functions callable from JavaScript ────────────────────────────────

# native_add(a, b) -> a + b
function native_add(ctx::Ptr{Cvoid})::Cint
    a = D.duk_get_number(ctx, 0)
    b = D.duk_get_number(ctx, 1)
    D.duk_push_number(ctx, a + b)
    return Cint(1)
end

# native_count() -> monotonically increasing counter held on the Julia side
const NATIVE_CALLS = Ref(0)
function native_count(ctx::Ptr{Cvoid})::Cint
    NATIVE_CALLS[] += 1
    D.duk_push_int(ctx, NATIVE_CALLS[])
    return Cint(1)
end

# native_throw() -> raises a TypeError inside the engine by returning a
# negative code, which duktape turns into a thrown error.
function native_throw(::Ptr{Cvoid})::Cint
    return Cint(DUK_RET_TYPE_ERROR)
end

@testset "Duktape Deep Tests" begin

@testset "Tier-1 slicing is live" begin
    @test !isempty(D.TIER1_FUNCTIONS)
    slices_dir = joinpath(PKG_DIR, "julia", "slices")
    @test isdir(slices_dir)
    lls = filter(f -> endswith(f, ".ll"), readdir(slices_dir))
    @test length(lls) == length(D.TIER1_FUNCTIONS)
    @test length(lls) > 200
    for f in first(sort(lls), 20)
        @test occursin("define", read(joinpath(slices_dir, f), String))
    end
    @test kernel_emits_llvmcall(D._TIER1_duk_get_top)
    @test kernel_emits_llvmcall(D._TIER1_duk_push_int)
end

@testset "Heap lifecycle" begin
    # Many independent heaps must be creatable and destroyable in sequence.
    for _ in 1:50
        ctx = D.duk_create_heap_default()
        @test ctx != C_NULL
        D.duk_destroy_heap(ctx)
    end
    @test true

    withheap() do ctx
        @test D.duk_get_top(ctx) == 0        # a fresh heap has an empty stack
    end
end

@testset "Value stack and type tags" begin
    withheap() do ctx
        D.duk_push_undefined(ctx)
        D.duk_push_null(ctx)
        D.duk_push_true(ctx)
        D.duk_push_false(ctx)
        D.duk_push_int(ctx, 42)
        D.duk_push_number(ctx, 2.5)
        D.duk_push_string(ctx, "text")
        D.duk_push_object(ctx)

        @test D.duk_get_top(ctx) == 8
        @test D.duk_get_top_index(ctx) == 7

        @test D.duk_get_type(ctx, 0) == DUK_TYPE_UNDEFINED
        @test D.duk_get_type(ctx, 1) == DUK_TYPE_NULL
        @test D.duk_get_type(ctx, 2) == DUK_TYPE_BOOLEAN
        @test D.duk_get_type(ctx, 3) == DUK_TYPE_BOOLEAN
        @test D.duk_get_type(ctx, 4) == DUK_TYPE_NUMBER
        @test D.duk_get_type(ctx, 5) == DUK_TYPE_NUMBER
        @test D.duk_get_type(ctx, 6) == DUK_TYPE_STRING
        @test D.duk_get_type(ctx, 7) == DUK_TYPE_OBJECT
        # An out-of-range index is NONE, not a crash.
        @test D.duk_get_type(ctx, 99) == DUK_TYPE_NONE

        @test D.duk_get_boolean(ctx, 2) == 1
        @test D.duk_get_boolean(ctx, 3) == 0
        @test D.duk_get_int(ctx, 4) == 42
        @test D.duk_get_number(ctx, 5) == 2.5
        @test D.duk_get_string(ctx, 6) == "text"

        @test D.duk_is_undefined(ctx, 0) == 1
        @test D.duk_is_null(ctx, 1) == 1
        @test D.duk_is_boolean(ctx, 2) == 1
        @test D.duk_is_number(ctx, 4) == 1
        @test D.duk_is_string(ctx, 6) == 1
        @test D.duk_is_object(ctx, 7) == 1
        @test D.duk_is_array(ctx, 7) == 0

        # Negative indices count from the top.
        @test D.duk_get_type(ctx, -1) == DUK_TYPE_OBJECT
        @test D.duk_get_string(ctx, -2) == "text"

        # Stack manipulation.
        D.duk_dup(ctx, 4)
        @test D.duk_get_top(ctx) == 9
        @test D.duk_get_int(ctx, -1) == 42
        D.duk_pop(ctx)
        @test D.duk_get_top(ctx) == 8
        D.duk_pop_n(ctx, 3)
        @test D.duk_get_top(ctx) == 5
        D.duk_set_top(ctx, 0)
        @test D.duk_get_top(ctx) == 0
    end
end

@testset "Evaluating ECMAScript" begin
    withheap() do ctx
        # Arithmetic and precedence are fixed by the language.
        for (src, want) in [("1 + 2 * 3", "7"),
                            ("(1 + 2) * 3", "9"),
                            ("7 / 2", "3.5"),
                            ("7 % 3", "1"),
                            ("2 ** 10", "1024"),
                            ("'a' + 'b'", "ab"),
                            ("[1,2,3].join('-')", "1-2-3"),
                            ("[3,1,2].sort().join(',')", "1,2,3"),
                            ("'abc'.toUpperCase()", "ABC"),
                            ("Math.max(1, 9, 5)", "9"),
                            ("JSON.stringify({a:1})", "{\"a\":1}"),
                            ("typeof undefined", "undefined"),
                            ("typeof null", "object"),
                            ("(function(){ return 6*7; })()", "42"),
                            ("[1,2,3].map(function(x){return x*2;}).join(',')", "2,4,6")]
            rc, s = evalstr(ctx, src)
            @test rc == DUK_EXEC_SUCCESS
            @test s == want
        end
        @test D.duk_get_top(ctx) == 0        # evalstr left the stack balanced
    end
end

@testset "Protected vs unprotected evaluation, errors" begin
    withheap() do ctx
        # A syntax error is caught by the protected form and reported.
        rc, msg = evalstr(ctx, "this is ( not javascript ]")
        @test rc == DUK_EXEC_ERROR
        @test occursin("SyntaxError", msg)

        # A runtime throw likewise.
        rc2, msg2 = evalstr(ctx, "throw new TypeError('deliberate')")
        @test rc2 == DUK_EXEC_ERROR
        @test occursin("TypeError", msg2)
        @test occursin("deliberate", msg2)

        # Referencing an undefined variable is a ReferenceError.
        rc3, msg3 = evalstr(ctx, "definitelyNotDefined")
        @test rc3 == DUK_EXEC_ERROR
        @test occursin("ReferenceError", msg3)

        # The error object survives on the stack long enough to classify.
        @test D.duk_peval_string(ctx, "throw new RangeError('r')") == DUK_EXEC_ERROR
        @test D.duk_is_object(ctx, -1) == 1
        @test D.duk_get_error_code(ctx, -1) == DUK_ERR_RANGE_ERROR
        D.duk_pop(ctx)

        # try/catch inside the script keeps evaluation successful.
        rc4, msg4 = evalstr(ctx, "try { null.x } catch (e) { 'caught ' + e.name }")
        @test rc4 == DUK_EXEC_SUCCESS
        @test msg4 == "caught TypeError"

        @test D.duk_get_top(ctx) == 0
    end
end

@testset "Objects, arrays and properties" begin
    withheap() do ctx
        # Build an object from C and read it back through JavaScript.
        D.duk_push_object(ctx)
        D.duk_push_int(ctx, 7)
        @test D.duk_put_prop_string(ctx, -2, "seven") == 1
        D.duk_push_string(ctx, "hello")
        D.duk_put_prop_string(ctx, -2, "greeting")
        D.duk_put_global_string(ctx, "fromC")

        rc, s = evalstr(ctx, "fromC.seven + ':' + fromC.greeting")
        @test rc == DUK_EXEC_SUCCESS
        @test s == "7:hello"

        # ...and the reverse: build in JavaScript, read from C.
        @test D.duk_peval_string(ctx, "({ a: 1, b: 'two', c: [10, 20, 30] })") ==
              DUK_EXEC_SUCCESS
        @test D.duk_is_object(ctx, -1) == 1

        @test D.duk_get_prop_string(ctx, -1, "a") == 1
        @test D.duk_get_int(ctx, -1) == 1
        D.duk_pop(ctx)

        @test D.duk_get_prop_string(ctx, -1, "b") == 1
        @test D.duk_get_string(ctx, -1) == "two"
        D.duk_pop(ctx)

        # A missing property reads as undefined and returns 0.
        @test D.duk_get_prop_string(ctx, -1, "missing") == 0
        @test D.duk_is_undefined(ctx, -1) == 1
        D.duk_pop(ctx)

        # Array access by index.
        @test D.duk_get_prop_string(ctx, -1, "c") == 1
        @test D.duk_is_array(ctx, -1) == 1
        @test D.duk_get_length(ctx, -1) == 3
        for (i, want) in enumerate((10, 20, 30))
            @test D.duk_get_prop_index(ctx, -1, i - 1) == 1
            @test D.duk_get_int(ctx, -1) == want
            D.duk_pop(ctx)
        end
        D.duk_pop(ctx)   # the array
        D.duk_pop(ctx)   # the object
        @test D.duk_get_top(ctx) == 0
    end
end

@testset "JSON encode / decode round-trip" begin
    withheap() do ctx
        # decode: string on the stack becomes an object in place
        D.duk_push_string(ctx, """{"n":42,"s":"str","arr":[1,2],"nested":{"k":true}}""")
        D.duk_json_decode(ctx, -1)
        @test D.duk_is_object(ctx, -1) == 1
        @test D.duk_get_prop_string(ctx, -1, "n") == 1
        @test D.duk_get_int(ctx, -1) == 42
        D.duk_pop(ctx)

        # encode: object becomes its JSON text
        s = D.duk_json_encode(ctx, -1)
        @test s !== nothing
        @test occursin("\"n\":42", s)
        @test occursin("\"nested\"", s)
        D.duk_pop(ctx)

        # Re-decoding the encoded form must be structurally identical, which
        # JavaScript itself can assert.
        D.duk_push_global_object(ctx)
        D.duk_pop(ctx)
        rc, out = evalstr(ctx, """
            var a = {n:42, s:"str", arr:[1,2], nested:{k:true}};
            JSON.stringify(JSON.parse(JSON.stringify(a))) === JSON.stringify(a)
        """)
        @test rc == DUK_EXEC_SUCCESS
        @test out == "true"

        @test D.duk_get_top(ctx) == 0
    end
end

@testset "Julia @cfunction native functions called from JavaScript" begin
    withheap() do ctx
        addf = @cfunction(native_add, Cint, (Ptr{Cvoid},))
        D.duk_push_c_function(ctx, addf, 2)
        D.duk_put_global_string(ctx, "nativeAdd")

        rc, s = evalstr(ctx, "nativeAdd(20, 22)")
        @test rc == DUK_EXEC_SUCCESS
        @test s == "42"

        # Called from inside a JavaScript closure, and repeatedly.
        rc2, s2 = evalstr(ctx, """
            var total = 0;
            for (var i = 0; i < 100; i++) { total = nativeAdd(total, i); }
            total
        """)
        @test rc2 == DUK_EXEC_SUCCESS
        @test s2 == string(sum(0:99))

        # A native function holding Julia-side state across calls.
        NATIVE_CALLS[] = 0
        cntf = @cfunction(native_count, Cint, (Ptr{Cvoid},))
        D.duk_push_c_function(ctx, cntf, 0)
        D.duk_put_global_string(ctx, "nativeCount")
        rc3, s3 = evalstr(ctx, "nativeCount(); nativeCount(); nativeCount()")
        @test rc3 == DUK_EXEC_SUCCESS
        @test s3 == "3"
        @test NATIVE_CALLS[] == 3        # the Julia side really ran three times

        # A native function that throws propagates as a JavaScript error and is
        # catchable in script — i.e. the longjmp crosses the Julia frame safely.
        thrf = @cfunction(native_throw, Cint, (Ptr{Cvoid},))
        D.duk_push_c_function(ctx, thrf, 0)
        D.duk_put_global_string(ctx, "nativeThrow")

        rc4, s4 = evalstr(ctx, "nativeThrow()")
        @test rc4 == DUK_EXEC_ERROR
        @test occursin("TypeError", s4)

        rc5, s5 = evalstr(ctx, "try { nativeThrow() } catch (e) { 'caught ' + e.name }")
        @test rc5 == DUK_EXEC_SUCCESS
        @test s5 == "caught TypeError"

        # The engine is still usable after the throw.
        rc6, s6 = evalstr(ctx, "nativeAdd(1, 1)")
        @test rc6 == DUK_EXEC_SUCCESS
        @test s6 == "2"

        @test D.duk_get_top(ctx) == 0
    end
end

@testset "Type coercion and string handling" begin
    withheap() do ctx
        # duk_safe_to_string must never throw, even on hostile values.
        for (src, want) in [("undefined", "undefined"),
                            ("null", "null"),
                            ("0/0", "NaN"),
                            ("1/0", "Infinity"),
                            ("-1/0", "-Infinity"),
                            ("[]", ""),
                            ("[1,2]", "1,2"),
                            ("({})", "[object Object]")]
            rc, s = evalstr(ctx, src)
            @test rc == DUK_EXEC_SUCCESS
            @test s == want
        end

        # An object whose toString throws still coerces safely.
        rc, s = evalstr(ctx, "({ toString: function(){ throw new Error('nope'); } })")
        @test rc == DUK_EXEC_SUCCESS
        @test s isa String              # some string came back; it did not throw

        # Unicode survives the round trip through the engine.
        D.duk_push_string(ctx, "héllo 日本 😀")
        @test D.duk_get_string(ctx, -1) == "héllo 日本 😀"
        D.duk_put_global_string(ctx, "uni")
        rc2, s2 = evalstr(ctx, "uni.length > 0 && uni.indexOf('日') >= 0")
        @test rc2 == DUK_EXEC_SUCCESS
        @test s2 == "true"

        @test D.duk_get_top(ctx) == 0
    end
end

@testset "Engine garbage collection and churn" begin
    withheap() do ctx
        # Allocate heavily inside the engine, drop it, and force a collection.
        rc, _ = evalstr(ctx, """
            var junk = [];
            for (var i = 0; i < 20000; i++) { junk.push('x' + i); }
            junk.length
        """)
        @test rc == DUK_EXEC_SUCCESS
        rc2, s2 = evalstr(ctx, "junk = null; 'dropped'")
        @test rc2 == DUK_EXEC_SUCCESS
        @test s2 == "dropped"
        D.duk_gc(ctx, 0)
        # The engine is still healthy after a forced GC.
        rc3, s3 = evalstr(ctx, "1 + 1")
        @test rc3 == DUK_EXEC_SUCCESS
        @test s3 == "2"
    end

    # Many short-lived heaps with Julia GC interleaved: a slice bound to a
    # stale allocator symbol shows up here rather than as a clean error.
    for i in 1:300
        withheap() do ctx
            @assert D.duk_peval_string(ctx, "var x = $i * 2; x") == DUK_EXEC_SUCCESS
            @assert D.duk_get_int(ctx, -1) == 2i
            D.duk_pop(ctx)
        end
        iszero(i % 100) && GC.gc()
    end
    @test true

    # Hammer the Tier-1 stack primitives in one long-lived heap.
    withheap() do ctx
        for i in 1:50_000
            D.duk_push_int(ctx, i)
            @assert D.duk_get_int(ctx, -1) == i
            D.duk_pop(ctx)
        end
        @test D.duk_get_top(ctx) == 0
        GC.gc()
    end
end

end  # top-level testset
